name: JoinLeaveMessages
main: me.darksavci.joinleavemessages.Main
version: 1.0
depend: [PlaceholderAPI]
commands: 
    jm-reload:
      description: Reload Config
      usage: '/jm-reload'
      permission: joinmessage.reload
      permission-message: "You don't have permission."
     